### PR TITLE
Optional TemperatureClient to redirect temperature readings another HA entity

### LINKED ISSUE #17: V0.0.3 not workig
The new update broke the thermostat for me. Is this generic?

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:360
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 16:21:17 (1 occurrences)
Last logged: 16:21:17
Error while setting up salusfy platform for climate

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/salusfy/climate.py", line 78, in async_setup_platform
    await async_setup_reload_service(hass, DOMAIN, PLATFORMS)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'async_setup_reload_service' is not defined
```

_Originally posted by @GigiPompieru in https://github.com/floringhimie/salusfy/issues/15#issuecomment-1883157033_

### PR DESCRIPTION
**Pull request by matthewturner**
Fixes #17, #19

I've been working on a fork for a while. I'm not sure if any of the changes are of interest but there may be some useful bits.

- Separated out components into discreet classes
- Added an **optional** `TemperatureClient` and `Client` wrapper to redirect temperature readings to another entity via the Home Assistant API
- Switched all calls to async
- Fixed various deprecation warnings
- Added run.py script for testing locally
- Added simulator classes
- Added unit tests
- Added devcontainers for running unit tests in VS Code
- Added Github CI

### CODE REVIEW

**Comment by romicaiarca** [comment]
I have installed your component and On run I have the following log message:

```yaml
climate:
  - platform: salusfy
    username: "email"
    password: "password"
    id: "salusDeviceId"
    enable_temperature_client: False
```
And it looks like the integration is looking for ```access_token``` and ```entity_id```. They should be set as optional and they should be required only if ```enable_temperature_client: True ```

To make the integration work, I had to add this into my config:

```yaml
climate:
  - platform: salusfy
    access_token: "your-HA-access-token"
    entity_id: "your-entity"
    username: "email"
    password: "password"
    id: "salusDeviceId"
    enable_temperature_client: False
```

**Comment by matthewturner** [comment]
Ah thanks, I hadn't tested without those values. I've made them optional now.

What was the log message you got?

**Comment by romicaiarca** [comment]
> Ah thanks, I hadn't tested without those values. I've made them optional now.
> 
> What was the log message you got?

```
Logger: homeassistant.config
Source: config.py:1293
First occurred: 10:50:55 AM (2 occurrences)
Last logged: 10:50:55 AM

Invalid config for 'climate' from integration 'salusfy' at custom_configs/salufy.yaml, line 2: required key 'access_token' not provided, please check the docs at https://github.com/floringhimie/salusfy Invalid config for 'climate' from integration 'salusfy' at custom_configs/salufy.yaml, line 2: required key 'entity_id' not provided, please check the docs at https://github.com/floringhimie/salusfy
```

I will try to fork and make a HACS compatible component from your fork with am instalation UI, in order to make the component more flexible and no pass passwords through config files.

**Comment by matthewturner** [comment]
I've just removed the extra settings from configuration.yaml and confirmed it now works correctly.

**Pull request closed without merging**
